// src/store/serverStore.ts
// Współdzielony globalny stan serwerowy dla środowiska izolowanego (Node.js/Next.js)

export function initializeMockData() {
  if (!(global as any).mockUsersStore) {
    (global as any).mockUsersStore = [
      { id: "1", email: "admin@celtronics.pl", username: "Admin", companyName: "Administrator Systemu", roleType: "ADMIN", isApproved: true, isBlocked: false, nip: null, jwt: "mock-jwt-admin", address: "ul. Główna 1, Siedlce", phone: "+48 111 222 333", createdAt: new Date(Date.now() - 30 * 86400000).toISOString(), discount: 0, tierName: "FULL ACCESS" },
      { id: "2", email: "instalator@celtronics.pl", username: "Instalator", companyName: "Instalator B2B (Tier A)", roleType: "BIZ", isApproved: true, isBlocked: false, nip: "1234567890", jwt: "mock-jwt-biz", address: "ul. Instalatorska 44, Warszawa", phone: "+48 999 888 777", createdAt: new Date(Date.now() - 15 * 86400000).toISOString(), discount: 15, tierName: "PARTNER SILVER" },
      { id: "3", email: "detal@celtronics.pl", username: "Detal", companyName: "Klient Detaliczny", roleType: "RETAIL", isApproved: true, isBlocked: false, nip: null, jwt: "mock-jwt-retail", address: "ul. Kwiatowa 2, Lublin", phone: "+48 444 555 666", createdAt: new Date(Date.now() - 2 * 86400000).toISOString(), discount: 0, tierName: "SKLEP DETAL" },
      { id: "4", email: "nowy@przyklad.pl", username: "Konrad", companyName: "Januszex Sp. z o.o.", roleType: "BIZ", isApproved: false, isBlocked: false, nip: "0987654321", jwt: "mock-jwt-new", address: "ul. Zamkowa 1, Kraków", phone: "+48 333 222 111", createdAt: new Date().toISOString(), discount: 5, tierName: "OCZEKUJĄCY" }
    ];
  }

  if (!(global as any).mockSolarStore) {
    (global as any).mockSolarStore = null;
  }

  if (!(global as any).mockCategoriesStore) {
    (global as any).mockCategoriesStore = [
      { id: "c1", name: "TV-SAT", iconName: "Tv", subcategories: [{ id: "s1", name: "Anteny TV FM DAB" }, { id: "s2", name: "Anteny SAT" }, { id: "s3", name: "Konwertery SAT" }, { id: "s4", name: "Multiswitche" }] },
      { id: "c2", name: "TELEFONIA KOMÓRKOWA", iconName: "Smartphone", subcategories: [{ id: "s5", name: "Anteny GSM" }, { id: "s6", name: "Wzmacniacze Gsm" }] },
      { id: "c3", name: "MONITORING", iconName: "Video", subcategories: [{ id: "s7", name: "Kamery IP" }, { id: "s8", name: "Kamery Analogowe" }, { id: "s9", name: "Rejestratory NVR" }] },
      { id: "c4", name: "WLAN, LAN", iconName: "Network", subcategories: [{ id: "s10", name: "Switche" }, { id: "s11", name: "Routery" }] },
      { id: "c7", name: "ALARMY", iconName: "Shield", subcategories: [{ id: "s12", name: "Centrale" }, { id: "s13", name: "Czujki" }] }
    ];
  }

  if (!(global as any).mockProductsStore || (global as any).mockProductsStore.length < 20) {
    (global as any).mockProductsStore = [
      { id: "p1", sku: "SAT-A1", name: "Antena Satelitarna Corab 80cm", categoryId: "c1", subcategoryId: "s2", manufacturer: "Corab", price: 125.00, stock: 45, seoDescription: "Profesjonalna antena satelitarna o średnicy 80cm, wykonana ze stali cynkowanej ogniowo, co zapewnia wysoką odporność na korozję. Konstrukcja uchwytu LNB oraz zblocza pozwala na stabilny odbior sygnału HD i 4K nawet w trudnych warunkach atmosferycznych. Idealna do instalacji indywidualnych oraz zbiorczych w domach jednorodzinnych." },
      { id: "p2", sku: "MON-IP-001", name: "Kamera Kopułkowa IP 4MP", categoryId: "c3", subcategoryId: "s7", manufacturer: "Hikvision", price: 290.00, stock: 120, seoDescription: "Zaawansowana kamera IP o rozdzielczości 4MP z technologią AcuSense, która skutecznie filtruje fałszywe alarmy wywoływane przez zwierzęta lub liście. Wyposażona w promiennik IR o zasięgu do 30m oraz funkcję WDR 120dB, gwarantującą czytelny obraz w warunkach wysokiego kontrastu oświetlenia. Obudowa o klasie szczelności IP67 pozwala na montaż na zewnątrz budynków." },
      { id: "p3", sku: "ALR-CTR-1", name: "Płyta Główna INTEGRA 32", categoryId: "c7", subcategoryId: "s12", manufacturer: "Satel", price: 410.00, stock: 12, seoDescription: "Serce zaawansowanego systemu alarmowego SATEL INTEGRA, obsługujące od 8 do 32 stref i wyjść. Centrala oferuje pełną integrację z systemami inteligentnego domu oraz kontroli dostępu, spełniając rygorystyczne normy bezpieczeństwa Grade 2 (EN 50131). Wbudowany dialer telefoniczny umożliwia szybkie powiadamianie i zdalne sterowanie systemem." },
      { id: "p4", sku: "LAN-SW-8", name: "Switch PoE 8-portowy", categoryId: "c4", subcategoryId: "s10", manufacturer: "Dahua", price: 195.00, stock: 30, seoDescription: "Wydajny przełącznik sieciowy wyposażony w 8 portów PoE+, zapewniający zasilanie i transmisję danych jednym kablem do kamer IP i telefonów VoIP. Posiada całkowity budżet mocy 60W oraz funkcję Extended PoE, pozwalającą na przesył sygnału na odległość do 250 metrów. Metalowa obudowa efektywnie odprowadza ciepło, gwarantując bezawaryjną pracę 24/7." },
      { id: "p5", sku: "SAT-K1", name: "Konwerter Quad Sharp", categoryId: "c1", subcategoryId: "s3", manufacturer: "Sharp", price: 85.00, stock: 20, seoDescription: "Wysokiej klasy konwerter satelitarny typu Quad, umożliwiający podłączenie do czterech niezależnych tunerów lub dwóch dekoderów z funkcją PVR. Charakteryzuje się bardzo niskim współczynnikiem szumów (0.1dB) oraz pełnym wsparciem dla transmisji 4K i 3D. Solidna obudowa z wysuwaną osłoną wtyków F chroni urządzenie przed wilgocią i uszkodzeniami." },
      { id: "p6", sku: "SAT-M1", name: "Multiswitch 5/8 Opticum", categoryId: "c1", subcategoryId: "s4", manufacturer: "Opticum", price: 140.00, stock: 8, seoDescription: "Niezawodny multiswitch do dystrybucji sygnału z jednej satelity i anteny naziemnej do 8 niezależnych gniazd abonenckich. Posiada wbudowany zasilacz oraz aktywny tor naziemny, co pozwala na wzmocnienie sygnału DVB-T2 bez konieczności stosowania dodatkowych wzmacniaczy. Idealny wybór do małych instalacji zbiorczych w budynkach wielorodzinnych." },
      { id: "p7", sku: "GSM-A1", name: "Antena ATK-10/800-980 MHz", categoryId: "c2", subcategoryId: "s5", manufacturer: "Diplol", price: 110.00, stock: 15, seoDescription: "Kierunkowa antena typu Yagi zaprojektowana do wzmocnienia sygnału telefonii komórkowej GSM i LTE w pasmie 800-980 MHz. Dzięki dużemu zyskowi energetycznemu (12.8 dBi) zapewnia stabilne połączenie internetowe i czyste rozmowy w miejscach o słabym zasięgu. Odporna na zmienne warunki pogodowe, dostarczana z kablem o długości 10m." },
      { id: "p8", sku: "MON-IP-002", name: "Kamera DS-2CD2143G2-I", categoryId: "c3", subcategoryId: "s7", manufacturer: "Hikvision", price: 345.00, stock: 25, seoDescription: "Wandaloodporna kamera IP 4MP z serii Pro, wyposażona w obiektyw szerokokątny 2.8mm i nowoczesne algorytmy kompresji H.265+. Oferuje funkcję ROI (Region of Interest) oraz zaawansowaną detekcję wtargnięcia i przekroczenia linii. Zintegrowany slot na kartę microSD do 256GB pozwala na lokalną archiwizację nagrań nawet w przypadku awarii sieci." },
      { id: "p9", sku: "MON-AN-001", name: "Kamera Analogowa HD-TVI 2MP", categoryId: "c3", subcategoryId: "s8", manufacturer: "Hikvision", price: 115.00, stock: 50, seoDescription: "Ekonomiczna kamera Turbo HD o rozdzielczości 1080p, kompatybilna ze standardami TVI, AHD, CVI i CVBS. Posiada promiennik EXIR 2.0 o zasięgu do 20m, który zapewnia równomierne doświetlenie sceny w całkowitej ciemności bez efektu 'białej plamy'. Doskonały wybór do modernizacji istniejących systemów analogowych na wysoką rozdzielczość." },
      { id: "p10", sku: "MON-REC-001", name: "Rejestrator 8CH NVR Dahua", categoryId: "c3", subcategoryId: "s9", manufacturer: "Dahua", price: 420.00, stock: 10, seoDescription: "Sieciowy rejestrator wideo obsługujący do 8 kamer IP o rozdzielczości do 8MP (4K). Wspiera zaawansowane kodowanie Smart H.265+ i posiada przepustowość przychodzącą na poziomie 80Mbps. Wyposażony w wyjście HDMI 4K oraz VGA, umożliwia podgląd na żywo i odtwarzanie z wielu kamer jednocześnie przez dedykowaną aplikację mobilną." },
      { id: "p11", sku: "LAN-RT-001", name: "Router MikroTik RB4011", categoryId: "c4", subcategoryId: "s11", manufacturer: "MikroTik", price: 750.00, stock: 5, seoDescription: "Potężny router klasy korporacyjnej wyposażony w 10 portów Gigabit Ethernet oraz slot SFP+ dla łączności 10Gbps. Napędzany czterordzeniowym procesorem ARM, oferuje bezkonkurencyjną wydajność routingu i wsparcie dla akceleracji IPSec. System RouterOS daje nieograniczone możliwości konfiguracji zaawansowanych sieci VPN, firewalli i VLANów." },
      { id: "p12", sku: "ALR-CZ-001", name: "Czujka RUCHU SLIM-PIR", categoryId: "c7", subcategoryId: "s13", manufacturer: "Satel", price: 55.00, stock: 100, seoDescription: "Cyfrowa czujka podczerwieni z nowatorskim algorytmem wykrywania ruchu, który minimalizuje ryzyko fałszywych alarmów przy jednoczesnym zachowaniu wysokiej czułości. Posiada certyfikat Grade 2, wbudowane rezystory parametryczne oraz wskaźnik LED z możliwością personalizacji koloru świecenia. Jej nowoczesny, smukły design idealnie komponuje się z wnętrzami." },
      { id: "p13", sku: "SAT-A2", name: "Antena 90cm Famaval", categoryId: "c1", subcategoryId: "s2", manufacturer: "Famaval", price: 160.00, stock: 12, seoDescription: "Wysokiej klasy antena satelitarna o średnicy 90cm, produkowana w Portugalii. Zastosowanie aluminium i stalowych elementów mocujących malowanych proszkowo gwarantuje wieloletnią trwałość w środowisku o dużej wilgotności. Większa powierzchnia czaszy zapewnia stabilny odbior sygnałów w jakości 4K nawet przy gęstym zachmurzeniu i opadach." },
      { id: "p14", sku: "MON-IP-003", name: "Kamera IP 8MP 4K", categoryId: "c3", subcategoryId: "s7", manufacturer: "Dahua", price: 580.00, stock: 18, seoDescription: "Profesjonalna kamera IP 4K z inteligentnym podświetleniem nocnym Full-Color, które pozwala na rejestrację kolorowego obrazu przez całą dobę. Przetwornik o wysokiej czułości oraz optyka o dużej jasności zapewniają widoczność szczegółów niedostępnych dla tradycyjnych kamer. Posiada mikrofon oraz wsparcie dla inteligentnej analityki AI (IVS)." },
      { id: "p15", sku: "LAN-SW-16", name: "Switch 16x 10/100/1000", categoryId: "c4", subcategoryId: "s10", manufacturer: "TP-Link", price: 230.00, stock: 7, seoDescription: "Niezarządzalny przełącznik typu Desktop/Rack wyposażony w 16 portów Gigabit Ethernet. Technologia Green TP-Link pozwala na znaczne obniżenie zużycia energii poprzez automatyczne dostosowanie mocy do długości podłączonych kabli. Prosta instalacja Plug&Play oraz stalowa obudowa czynią go idealnym rozwiązaniem do rozbudowy sieci firmowej." },
      { id: "p16", sku: "ALR-CTR-2", name: "Centrala PERFECTA 16", categoryId: "c7", subcategoryId: "s12", manufacturer: "Satel", price: 320.00, stock: 14, seoDescription: "Nowoczesna centrala alarmowa zaprojektowana do ochrony domów, mieszkań i małych biur. Posiada wbudowany moduł komunikacyjny GSM/GPRS, który umożliwia łatwe sterowanie systemem przez aplikację mobilną oraz tradycyjne powiadamianie głosowe i SMS. Obsługuje 16 stref i 4 partycje, oferując funkcję weryfikacji akustycznej alarmu." },
      { id: "p17", sku: "SAT-K2", name: "Konwerter Twin Inverto", categoryId: "c1", subcategoryId: "s3", manufacturer: "Inverto", price: 65.00, stock: 30, seoDescription: "Konwerter typu Twin z legendarnej serii Black Ultra, znany z bezkompromisowej jakości odbioru przy niskim poziomie sygnału. Dwa niezależne wyjścia pozwalają na podłączenie dwóch odbiorników jedno-głowicowych lub jednego typu PVR (dual-tuner). Zoptymalizowany pod kątem odbioru pasm High-Definition, zapewnia niski poziom zakłóceń fazowych." },
      { id: "p18", sku: "GSM-W1", name: "Wzmacniacz GSM Turbo-Room", categoryId: "c2", subcategoryId: "s6", manufacturer: "Signal", price: 890.00, stock: 3, seoDescription: "Kompletny zestaw wzmacniający sygnał GSM wewnątrz budynków, wyposażony w funkcję AGC (Auto Gain Control). Eliminuje problem 'zrywania połączeń' w biurach, magazynach i piwnicach o grubych murach lub dużej odległości od stacji bazowej. Zestaw zawiera antenę zewnętrzną, wewnętrzną oraz niezbędne okablowanie, nie wymagając konfiguracji." },
      { id: "p19", sku: "MON-IP-004", name: "Kamera WiFi Tuya Smart", categoryId: "c3", subcategoryId: "s7", manufacturer: "Inny", price: 145.00, stock: 40, seoDescription: "Mobilna kamera IP WiFi zintegrowana z najpopularniejszym ekosystemem inteligentnego domu Tuya Smart. Oferuje dwukierunkową komunikację audio (głośnik + mikrofon), śledzenie ruchu oraz tryb nocny z diodami LED. Idealne rozwiązanie do niani elektronicznej lub monitoringu mieszkania, niewymagające rejestratora ani skomplikowanej instalacji." },
      { id: "p20", sku: "ALR-CZ-002", name: "Czujka Zalania WL-2", categoryId: "c7", subcategoryId: "s13", manufacturer: "Satel", price: 82.00, stock: 22, seoDescription: "Precyzyjna czujka wycieku wody przeznaczona do instalacji w pralniach, łazienkach i kotłowniach. Wyposażona w zewnętrzną sondę na giętkim przewodzie, pozwala na monitoring nawet trudno dostępnych miejsc pod urządzeniami AGD. Wykrycie zalania natychmiast wyzwala alarm, co pozwala zapobiec kosztownym zniszczeniom mienia." },
      { id: "p21", sku: "LAN-RT-002", name: "Router ASUS RT-AX58U", categoryId: "c4", subcategoryId: "s11", manufacturer: "Asus", price: 440.00, stock: 6, seoDescription: "Dwupasmowy router WiFi 6 (802.11ax) o łącznej przepustowości do 3000 Mbps. Wyposażony w technologie OFDMA i MU-MIMO, zapewnia płynne działanie sieci przy wielu podłączonych urządzeniach jednocześnie. Pakiet AiProtection Pro od Trend Micro gwarantuje darmowe, dożywotnie bezpieczeństwo Twojej domowej sieci przed atakami z internetu." },
      { id: "p22", sku: "SAT-M2", name: "Multiswitch 9/16 Terra", categoryId: "c1", subcategoryId: "s4", manufacturer: "Terra", price: 520.00, stock: 4, seoDescription: "Profesjonalny multiswitch radialny klasy A, przeznaczony do dużych instalacji zbiorczych obsługujących dwa satelity (np. HotBird + Astra) i sygnał naziemny. Posiada 9 wejść i 16 wyjść abonenckich z wbudowaną korekcją strat kabla na każdym torze. Odlewana obudowa zapewnia najwyższy poziom ekranowania i odporność na zakłócenia LTE." },
      { id: "p23", sku: "MON-REC-002", name: "NVR 16CH Hikvision 7616", categoryId: "c3", subcategoryId: "s9", manufacturer: "Hikvision", price: 980.00, stock: 2, seoDescription: "Wydajny rejestrator sieciowy 16-kanałowy, obsługujący dwa dyski twarde SATA o pojemności do 10TB każdy. Wyposażony we wsparcie dla inteligentnych kamer IP oraz funkcję Dual-OS, zapewniającą ciągłość pracy w przypadku awarii systemu operacyjnego. Obsługuje nowoczesne standardy analityki VCA oraz zdalne zarządzanie poprzez chmurę Hik-Connect." },
      { id: "p24", sku: "ALR-CZ-003", name: "Czujka Magnetyczna B-3", categoryId: "c7", subcategoryId: "s13", manufacturer: "Satel", price: 12.00, stock: 250, seoDescription: "Uniwersalna cyfrowa czujka kontaktronowa typu bocznego, przeznaczona do ochrony obwodowej drzwi i okien. Mała, estetyczna obudowa z tworzywa sztucznego pozwala na dyskretny montaż nawierzchniowy. Wysoka trwałość styków magnetycznych gwarantuje niezawodne działanie przez dziesiątki tysięcy cykli otwarcia i zamknięcia." },
      { id: "p25", sku: "SAT-A3", name: "Antena Tri Digit UHF", categoryId: "c1", subcategoryId: "s1", manufacturer: "Diplol", price: 135.00, stock: 20, seoDescription: "Trójramienna antena kierunkowa wysokiego zysku, przeznaczona do odbioru naziemnej telewizji cyfrowej DVB-T2 w standardzie HEVC. Konstrukcja z anodowanego aluminium jest lekka i wysoce odporna na wiatr. Wbudowany filtr LTE 4G/5G eliminuje zakłócenia pochodzące z nadajników telefonii komórkowej, zapewniając stabilny obraz HD." }
    ];
  }

  if (!(global as any).mockOrdersStore) {
    (global as any).mockOrdersStore = [];
  }

  if (!(global as any).mockRepairsStore) {
    (global as any).mockRepairsStore = [
      { id: "RMA-001", clientEmail: "instalator@celtronics.pl", device: "Kamera IP CAM-1", description: "Brak zasilania po burzy", status: "PENDING", createdAt: new Date().toISOString() },
      { id: "RMA-002", clientEmail: "detal@celtronics.pl", device: "Rejestrator 4CH", description: "Nie czyta dysku twardego", status: "IN_PROGRESS", createdAt: new Date(Date.now() - 3 * 86400000).toISOString() }
    ];
  }

  return {
    users: (global as any).mockUsersStore,
    orders: (global as any).mockOrdersStore,
    repairs: (global as any).mockRepairsStore,
    categories: (global as any).mockCategoriesStore,
    products: (global as any).mockProductsStore
  };
}
